spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  h2:
    console:
      enabled: true

weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: 1b297b295863eeec3699027cbfd8670e

resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 10s

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
